# Generated by Django 4.0 on 2022-03-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='blood',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Blood Group'),
        ),
    ]
