# Generated by Django 4.0 on 2022-03-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='blood'),
        ),
    ]
