# Generated by Django 4.0 on 2022-03-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_bloodrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
