# Generated by Django 4.0 on 2022-03-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_event_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
