# Generated by Django 4.0 on 2022-04-10 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_feedback_like_feedbacklike'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientToDonorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('blood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.blood')),
                ('from_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='From+', to='app.customuser')),
                ('to_donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='To+', to='app.customuser')),
            ],
        ),
    ]
