# Generated by Django 4.0 on 2022-04-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_patienttodonorrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientToDonorRequest',
            new_name='RequestToDonor',
        ),
    ]
